import type { InventoryCategory, InventoryItem, StockAlert, StorageCondition, Supplier, Unit } from "@/types/inventory";

export const mockSuppliers: Supplier[] = [
  {
    id: 1,
    name: "Ayurvedic Herbs & Oils Co.",
    contactPerson: "Rajesh Kumar",
    phone: "+91 9876543210",
    email: "rajesh@ayurvedicherbs.com",
    address: "123 Herbal Lane, Mumbai, Maharashtra 400001",
    paymentTerms: "Net 30",
    status: "Active",
  },
  {
    id: 2,
    name: "Traditional Medicine Supplies",
    contactPerson: "Priya Sharma",
    phone: "+91 9876543211",
    email: "priya@tradmed.com",
    address: "456 Medicine Street, Delhi, Delhi 110001",
    paymentTerms: "Net 15",
    status: "Active",
  },
  {
    id: 3,
    name: "Wellness Equipment Ltd",
    contactPerson: "Amit Patel",
    phone: "+91 9876543212",
    email: "amit@wellnessequip.com",
    address: "789 Equipment Road, Bangalore, Karnataka 560001",
    paymentTerms: "Net 45",
    status: "Active",
  },
];

export const mockInventoryCategories: InventoryCategory[] = [
  { id: 1, name: "Medicinal Oils", description: "Various therapeutic oils used in treatments" },
  { id: 2, name: "Herbs & Spices", description: "Medicinal herbs and spices for treatments" },
  { id: 3, name: "Equipment", description: "Medical equipment and tools" },
  { id: 4, name: "Consumables", description: "Disposable items and consumables" },
  { id: 5, name: "Powders", description: "Medicinal powders and formulations" },
];

export const mockUnits: Unit[] = [
  { id: 1, name: "Kilogram", abbreviation: "kg" },
  { id: 2, name: "Liter", abbreviation: "lit" },
  { id: 3, name: "Pieces", abbreviation: "pcs" },
  { id: 4, name: "Bottles", abbreviation: "bottles" },
  { id: 5, name: "Milliliter", abbreviation: "ml" },
  { id: 6, name: "Gram", abbreviation: "g" },
  { id: 7, name: "Boxes", abbreviation: "boxes" },
];

export const mockStorageConditions: StorageCondition[] = [
  { id: 1, name: "Room Temperature", description: "Store at 20-25°C" },
  { id: 2, name: "Refrigerated", description: "Store at 2-8°C" },
  { id: 3, name: "Frozen", description: "Store below 0°C" },
  { id: 4, name: "Dry Storage", description: "Store in dry, cool place" },
  { id: 5, name: "Protected from Light", description: "Store away from direct sunlight" },
];

export const mockInventoryItems: InventoryItem[] = [
  {
    id: 1,
    itemName: "Sesame Oil (Til Oil)",
    itemCategory: "Medicinal Oils",
    batchNo: "BATCH-001-2024",
    quantity: 15.5,
    unit: "lit",
    manufacturingDate: "2024-01-15",
    expiryDate: "2025-01-15",
    storageCondition: "Room Temperature",
    storageLocation: "Storage Room A - Shelf 1",
    remarks: "Premium quality sesame oil for Abhyanga",
    supplierName: "Ayurvedic Herbs & Oils Co.",
    supplierId: 1,
    status: "Active",
    createdDate: "2024-01-20",
    updatedDate: "2024-01-20",
  },
  {
    id: 2,
    itemName: "Coconut Oil",
    itemCategory: "Medicinal Oils",
    batchNo: "BATCH-002-2024",
    quantity: 8.2,
    unit: "lit",
    manufacturingDate: "2024-02-01",
    expiryDate: "2025-02-01",
    storageCondition: "Room Temperature",
    storageLocation: "Storage Room A - Shelf 2",
    remarks: "Organic coconut oil for head massage",
    supplierName: "Ayurvedic Herbs & Oils Co.",
    supplierId: 1,
    status: "Low Stock",
    createdDate: "2024-02-05",
    updatedDate: "2024-02-05",
  },
  {
    id: 3,
    itemName: "Turmeric Powder",
    itemCategory: "Powders",
    batchNo: "BATCH-003-2024",
    quantity: 2.5,
    unit: "kg",
    manufacturingDate: "2024-01-10",
    expiryDate: "2025-01-10",
    storageCondition: "Dry Storage",
    storageLocation: "Storage Room B - Shelf 3",
    remarks: "High quality turmeric for face packs",
    supplierName: "Traditional Medicine Supplies",
    supplierId: 2,
    status: "Active",
    createdDate: "2024-01-15",
    updatedDate: "2024-01-15",
  },
  {
    id: 4,
    itemName: "Massage Table",
    itemCategory: "Equipment",
    batchNo: "EQ-001-2024",
    quantity: 3,
    unit: "pcs",
    manufacturingDate: "2024-01-01",
    expiryDate: "2030-01-01",
    storageCondition: "Room Temperature",
    storageLocation: "Treatment Room 1",
    remarks: "Professional massage table with adjustable height",
    supplierName: "Wellness Equipment Ltd",
    supplierId: 3,
    status: "Active",
    createdDate: "2024-01-05",
    updatedDate: "2024-01-05",
  },
  {
    id: 5,
    itemName: "Neem Leaves",
    itemCategory: "Herbs & Spices",
    batchNo: "BATCH-004-2024",
    quantity: 0.5,
    unit: "kg",
    manufacturingDate: "2024-01-20",
    expiryDate: "2024-07-20",
    storageCondition: "Dry Storage",
    storageLocation: "Storage Room B - Shelf 4",
    remarks: "Fresh neem leaves for detox treatments",
    supplierName: "Traditional Medicine Supplies",
    supplierId: 2,
    status: "Expired",
    createdDate: "2024-01-25",
    updatedDate: "2024-01-25",
  },
  {
    id: 6,
    itemName: "Cotton Towels",
    itemCategory: "Consumables",
    batchNo: "CONS-001-2024",
    quantity: 25,
    unit: "pcs",
    manufacturingDate: "2024-01-01",
    expiryDate: "2025-01-01",
    storageCondition: "Room Temperature",
    storageLocation: "Linen Room",
    remarks: "100% cotton towels for treatments",
    supplierName: "Traditional Medicine Supplies",
    supplierId: 2,
    status: "Active",
    createdDate: "2024-01-10",
    updatedDate: "2024-01-10",
  },
  {
    id: 7,
    itemName: "Ashwagandha Powder",
    itemCategory: "Powders",
    batchNo: "BATCH-005-2024",
    quantity: 1.0,
    unit: "kg",
    manufacturingDate: "2024-02-10",
    expiryDate: "2025-02-10",
    storageCondition: "Dry Storage",
    storageLocation: "Storage Room B - Shelf 5",
    remarks: "Premium Ashwagandha for stress relief",
    supplierName: "Traditional Medicine Supplies",
    supplierId: 2,
    status: "Low Stock",
    createdDate: "2024-02-15",
    updatedDate: "2024-02-15",
  },
  {
    id: 8,
    itemName: "Ghee (Clarified Butter)",
    itemCategory: "Medicinal Oils",
    batchNo: "BATCH-006-2024",
    quantity: 5.0,
    unit: "kg",
    manufacturingDate: "2024-01-30",
    expiryDate: "2024-07-30",
    storageCondition: "Refrigerated",
    storageLocation: "Refrigerator - Shelf 2",
    remarks: "Pure cow ghee for internal consumption",
    supplierName: "Ayurvedic Herbs & Oils Co.",
    supplierId: 1,
    status: "Expiring Soon",
    createdDate: "2024-02-05",
    updatedDate: "2024-02-05",
  },
];

export const mockStockAlerts: StockAlert[] = [
  {
    id: 1,
    itemId: 2,
    itemName: "Coconut Oil",
    alertType: "Low Stock",
    message: "Coconut Oil quantity is below minimum threshold (10 lit)",
    severity: "Medium",
    createdAt: "2024-02-20",
  },
  {
    id: 2,
    itemId: 5,
    itemName: "Neem Leaves",
    alertType: "Expired",
    message: "Neem Leaves have expired on 2024-07-20",
    severity: "High",
    createdAt: "2024-07-21",
  },
  {
    id: 3,
    itemId: 7,
    itemName: "Ashwagandha Powder",
    alertType: "Low Stock",
    message: "Ashwagandha Powder quantity is below minimum threshold (2 kg)",
    severity: "Medium",
    createdAt: "2024-02-20",
  },
  {
    id: 4,
    itemId: 8,
    itemName: "Ghee (Clarified Butter)",
    alertType: "Expiring Soon",
    message: "Ghee will expire in 30 days (2024-07-30)",
    severity: "High",
    createdAt: "2024-06-30",
  },
];
